language: android
dist: trusty

env:
  - release=android release_notes="for test" notify="true"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - OLDPATH=$PATH
  - export PATH=$JAVA_HOME/bin:$PATH
  - echo yes | sdkmanager "build-tools;30.0.3"
  - echo yes | sdkmanager "platforms;android-31"
  - export JAVA_HOME=~/openjdk11
  - export PATH=$OLDPATH

jdk: openjdk11
script: 
  - ./gradlew assembleDebug
  - export INSTALL_DIR=/tmp
  - curl -Ls https://github.com/Massad/cli/releases/latest/download/install | bash
  - $INSTALL_DIR/ta-cli publish --api_token=$TESTAPP_API_TOKEN --app_id=$APP_ID --release=$release  --apk=./app/build/outputs/apk/debug/app-debug.apk --release_notes=$release_notes --notify=$notify --source=TravisCI
