version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-upload:
    executor:
      name: android/android-machine
    environment:
      release: android
      release_notes: "for test"
      notify: "true"
    steps:
      # Checkout the code as the first step.
      - checkout
      # And next run the debug build
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug
      - run:
          name: upload to testapp.io
          command: |
            export INSTALL_DIR=$CIRCLE_WORKING_DIRECTORY
            curl -Ls https://github.com/Massad/cli/releases/latest/download/install | bash
            $CIRCLE_WORKING_DIRECTORY/ta-cli publish --api_token=$TESTAPP_API_TOKEN --app_id=$app_id --release=$release  --apk=$CIRCLE_WORKING_DIRECTORY/app/build/outputs/apk/debug/app-debug.apk --release_notes=$release_notes --notify=$notify --source=circleci
workflows:
  default: 
    jobs:
      - build-and-upload
